name: niimbot_print
description: Niimbot Printer Integration
version: 0.0.4
homepage: zh4.dev

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  permission_handler: ^12.0.0+1
  flutter_blue_plus: ^2.0.0
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zh4dev.niimbot_print
        pluginClass: NiimbotPrintPlugin
      ios:
        pluginClass: NiimbotPrintPlugin
      linux:
        pluginClass: NiimbotPrintPlugin
      macos:
        pluginClass: NiimbotPrintPlugin
      windows:
        pluginClass: NiimbotPrintPluginCApi
